'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class TestPage

	''' <summary>
	''' form1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' ASPxComboBox1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ASPxComboBox1 As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

	''' <summary>
	''' DropDownList1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected DropDownList1 As Global.System.Web.UI.WebControls.DropDownList

	''' <summary>
	''' ASPxComboBox2 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ASPxComboBox2 As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

	''' <summary>
	''' ObjectDataSource1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ObjectDataSource1 As Global.System.Web.UI.WebControls.ObjectDataSource

	''' <summary>
	''' SqlDataSource1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
